Reporting functional test only on all pass (#1)
* Reporting functional test only on all pass

Signed-off-by: willdavsmith <willdavsmith@gmail.com>

* test

Signed-off-by: willdavsmith <willdavsmith@gmail.com>

* test

Signed-off-by: willdavsmith <willdavsmith@gmail.com>

* test

Signed-off-by: willdavsmith <willdavsmith@gmail.com>

* test

Signed-off-by: willdavsmith <willdavsmith@gmail.com>

* test

Signed-off-by: willdavsmith <willdavsmith@gmail.com>

* test

Signed-off-by: willdavsmith <willdavsmith@gmail.com>

* test

Signed-off-by: willdavsmith <willdavsmith@gmail.com>

---------

Signed-off-by: willdavsmith <willdavsmith@gmail.com>

diff --git a/.github/workflows/functional-test.yaml b/.github/workflows/functional-test.yaml
--- a/.github/workflows/functional-test.yaml
+++ b/.github/workflows/functional-test.yaml
@@ -16,6 +16,7 @@
 
 name: Functional tests
 on:
+  workflow_dispatch:
   schedule:
     # Run every 4 hours on weekdays.
     - cron: "30 0,4,8,12,16,20 * * 1-5"
@@ -75,11 +76,10 @@ jobs:
   build:
     name: Build Radius for test
     runs-on: ubuntu-latest
-    if: github.event_name == 'repository_dispatch' || (github.event_name == 'schedule' && github.repository == 'radius-project/radius') || github.event_name == 'workflow_run'
+    if: github.event_name == 'repository_dispatch' || (github.event_name == 'schedule' && github.repository == 'willdavsmith/radius') || github.event_name == 'workflow_run'
     env:
       DE_IMAGE: 'ghcr.io/radius-project/deployment-engine'
       DE_TAG: 'latest'
-      FUNCTIONAL_TEST_APP_ID: 425843
     outputs:
       REL_VERSION: ${{ steps.gen-id.outputs.REL_VERSION }}
       UNIQUE_ID: ${{ steps.gen-id.outputs.UNIQUE_ID }}
@@ -94,18 +94,18 @@ jobs:
         uses: tibdex/github-app-token@v1
         id: get_installation_token
         with: 
-          app_id: ${{ env.FUNCTIONAL_TEST_APP_ID }}
+          app_id: ${{ secrets.FUNCTIONAL_TEST_APP_ID }}
           private_key: ${{ secrets.FUNCTIONAL_TEST_APP_PRIVATE_KEY }}
       - name: Set up checkout target (scheduled)
         if: github.event_name == 'schedule'
         run: |
           echo "CHECKOUT_REPO=${{ github.repository }}" >> $GITHUB_ENV
-          echo "CHECKOUT_REF=refs/heads/main" >> $GITHUB_ENV
+          echo "CHECKOUT_REF=refs/heads/willdavsmith/functional-test-pass" >> $GITHUB_ENV
       - name: Set up checkout target (pull_request)
         if: github.event_name == 'pull_request'
         run: |
             echo "CHECKOUT_REPO=${{ github.repository }}" >> $GITHUB_ENV
-            echo "CHECKOUT_REF=${{ github.ref }}" >> $GITHUB_ENV
+            echo "CHECKOUT_REF=refs/heads/willdavsmith/functional-test-pass" >> $GITHUB_ENV
             echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
       - name: Use custom actions
         uses: actions/checkout@v3
@@ -302,7 +302,7 @@ jobs:
   tests:
     name: Run ${{ matrix.name }} functional tests
     needs: build
-    if: github.event_name == 'repository_dispatch' || (github.event_name == 'schedule' && github.repository == 'radius-project/radius') || github.event_name == 'workflow_run'
+    if: github.event_name == 'repository_dispatch' || (github.event_name == 'schedule' && github.repository == 'willdavsmith/radius') || github.event_name == 'workflow_run'
     strategy:
       fail-fast: true
       matrix:
@@ -324,13 +324,14 @@ jobs:
       BICEP_RECIPE_TAG_VERSION: ${{ needs.build.outputs.REL_VERSION }}
       DE_IMAGE: ${{ needs.build.outputs.DE_IMAGE }}
       DE_TAG: ${{ needs.build.outputs.DE_TAG }}
-      FUNCTIONAL_TEST_APP_ID: 425843
+    outputs:
+      test_status: ${{ steps.report_test_status.outputs.test_status }}
     steps:
       - name: Login as the GitHub App
         uses: tibdex/github-app-token@v1
         id: get_installation_token
         with: 
-          app_id: ${{ env.FUNCTIONAL_TEST_APP_ID }}
+          app_id: ${{ secrets.FUNCTIONAL_TEST_APP_ID }}
           private_key: ${{ secrets.FUNCTIONAL_TEST_APP_PRIVATE_KEY }}
       - uses: LouisBrunner/checks-action@v1.6.1
         if: always()
@@ -628,6 +629,29 @@ jobs:
           append: true
           message: |
             :x: ${{ matrix.name }} functional test cancelled. Please check [the logs](${{ env.ACTION_LINK }}) for more details
+      - id: report_test_status
+        if: always()
+        run: |
+          if ${{ env.test_status }} == 'failure' || ${{ job.status }} == 'failure' || ${{ job.status }} == 'cancelled'; then
+            echo "test_status=failure" >> $GITHUB_OUTPUT
+            echo "test_status=failure" >> $GITHUB_ENV
+          else
+            echo "test_status=success" >> $GITHUB_OUTPUT
+          fi
+  report-test-results:
+    name: Report test results
+    needs: [build, tests]
+    runs-on: ubuntu-latest
+    if: always()
+    env:
+      CHECKOUT_REF: ${{ needs.build.outputs.CHECKOUT_REF }}
+    steps:
+      - name: Login as the GitHub App
+        uses: tibdex/github-app-token@v1
+        id: get_installation_token
+        with:
+          app_id: ${{ secrets.FUNCTIONAL_TEST_APP_ID }}
+          private_key: ${{ secrets.FUNCTIONAL_TEST_APP_PRIVATE_KEY }}
       - uses: LouisBrunner/checks-action@v1.6.1
         if: always()
         with:
@@ -636,7 +660,7 @@ jobs:
           repo: ${{ github.repository }}
           sha: ${{ env.CHECKOUT_REF }}
           status: completed
-          conclusion: ${{ job.status }}
+          conclusion: ${{ needs.tests.outputs.test_status }}
           output: |
             {"summary":"Functional Test run completed. See links for more information.","title":"Functional Test Run"}
           details_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
@@ -644,7 +668,7 @@ jobs:
     name: Report test failure
     needs: [build, tests]
     runs-on: ubuntu-latest
-    if: failure() && github.event_name == 'schedule' && github.repository == 'radius-project/radius'
+    if: failure() && github.event_name == 'schedule' && github.repository == 'willdavsmith/radius'
     steps:
       - name: Create failure issue for failing scheduled run
         uses: actions/github-script@v6
